export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';